version: '3.8'

services:
  vector-db-main:
    build:
      context: ./main-module
      dockerfile: Dockerfile
    container_name: vector-db-main
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - STORAGE_MODULE_HOST=vector-db-storage
      - STORAGE_MODULE_PORT=8081
      - STORAGE_MODULE_CONNECTION_TIMEOUT=5000
      - STORAGE_MODULE_READ_TIMEOUT=10000
      - JAVA_OPTS=-Xms512m -Xmx1g -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      vector-db-storage:
        condition: service_healthy
    networks:
      - vector-db-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vector-db-storage:
    build:
      context: ./storage-module
      dockerfile: Dockerfile
    container_name: vector-db-storage
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VECTOR_DB_STORAGE_DATA_PATH=/app/data
      - VECTOR_DB_STORAGE_SHARD_ID=shard-1
      - SERVER_PORT=8081
      - JAVA_OPTS=-Xms1g -Xmx2g -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Djava.library.path=/usr/lib/x86_64-linux-gnu
    volumes:
      - vector-db-data:/app/data
      - vector-db-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/storage/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - vector-db-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  vector-db-data:
    driver: local
  vector-db-logs:
    driver: local

networks:
  vector-db-network:
    driver: bridge
