version: '3.8'

services:
  vector-db-main:
    build:
      context: ./main-module
      dockerfile: Dockerfile
    container_name: vector-db-main
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VECTOR_DB_CLUSTER_SHARDS_0_HOST=vector-db-storage-1
      - VECTOR_DB_CLUSTER_SHARDS_0_PORT=8081
      - VECTOR_DB_CLUSTER_SHARDS_1_HOST=vector-db-storage-2
      - VECTOR_DB_CLUSTER_SHARDS_1_PORT=8081
      - JAVA_OPTS=-Xms512m -Xmx1g -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom
    depends_on:
      vector-db-storage-1:
        condition: service_healthy
      vector-db-storage-2:
        condition: service_healthy
    networks:
      - vector-db-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vector-db-storage-1:
    build:
      context: ./storage-module
      dockerfile: Dockerfile
    container_name: vector-db-storage-1
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VECTOR_DB_STORAGE_DATA_PATH=/app/data
      - VECTOR_DB_STORAGE_SHARD_ID=shard-1
      - SERVER_PORT=8081
      - JAVA_OPTS=-Xms1g -Xmx2g -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Djava.library.path=/usr/lib/x86_64-linux-gnu
    volumes:
      - vector-db-shard-1-data:/app/data
      - vector-db-shard-1-logs:/app/logs
    networks:
      - vector-db-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2.5G
        reservations:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vector-db-storage-2:
    build:
      context: ./storage-module
      dockerfile: Dockerfile
    container_name: vector-db-storage-2
    ports:
      - "8082:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VECTOR_DB_STORAGE_DATA_PATH=/app/data
      - VECTOR_DB_STORAGE_SHARD_ID=shard-2
      - SERVER_PORT=8081
      - JAVA_OPTS=-Xms1g -Xmx2g -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Djava.library.path=/usr/lib/x86_64-linux-gnu
    volumes:
      - vector-db-shard-2-data:/app/data
      - vector-db-shard-2-logs:/app/logs
    networks:
      - vector-db-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2.5G
        reservations:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  vector-db-shard-1-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/shard-1
  vector-db-shard-1-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs/shard-1
  vector-db-shard-2-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/shard-2
  vector-db-shard-2-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs/shard-2

networks:
  vector-db-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
